services:
  # Шаблон первого инстанса (будет на порту 8081)
  onlyoffice-1: &onlyoffice_template
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-docs-1
    restart: always
    ports:
      - "${PORT_1}:80"
    deploy:
      resources:
        limits:
          memory: ${OFFICE_MEM_LIMIT}
          cpus: ${OFFICE_CPU_LIMIT}
        reservations:
          memory: ${OFFICE_MEM_RESERVE} 
    environment:
       - JWT_ENABLED=true
       - JWT_SECRET=${JWT_SECRET}
       - JWT_HEADER=AuthorizationJwt
       - FORWARDED_FOR_HEADERS=X-Forwarded-Proto X-Forwarded-Host
       - FORCE_SSL=true

  # Второй инстанс автоматически копирует всё из первого
  onlyoffice-2:
    <<: *onlyoffice_template
    container_name: onlyoffice-docs-2
    ports:
     - "${PORT_2}:80"