services:
  # Шаблон первого инстанса (будет на порту 8081)
  onlyoffice-1: &onlyoffice_template
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-docs-1
    restart: always
    ports:
      - "${PORT_1}:80"
    deploy:
      resources:
        limits:
          memory: ${OFFICE_MEM_LIMIT}
          cpus: ${OFFICE_CPU_LIMIT}
        reservations:
          memory: ${OFFICE_MEM_RESERVE} 
    environment:
       - JWT_ENABLED=true
       - JWT_SECRET=${JWT_SECRET}
       - JWT_HEADER=AuthorizationJwt
       - FORWARDED_FOR_HEADERS=X-Forwarded-Proto X-Forwarded-Host
       - FORCE_SSL=true
    volumes:
      - ./plugins/ai/config.json:/var/www/onlyoffice/documentserver/sdkjs-plugins/{9DC93CDB-B576-4F0C-B55E-FCC9C48DD007}/scripts/engine/providers/config.json:ro
      - ./plugins/ai/aitech.js:/var/www/onlyoffice/documentserver/sdkjs-plugins/{9DC93CDB-B576-4F0C-B55E-FCC9C48DD007}/scripts/engine/providers/internal/aitech.js:ro

  # Второй инстанс автоматически копирует всё из первого
  onlyoffice-2:
    <<: *onlyoffice_template
    container_name: onlyoffice-docs-2
    ports:
     - "${PORT_2}:80"